providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps || npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

[variables]
NIXPACKS_NODE_VERSION = "20.18.0"
NODE_VERSION = "20.18.0"
NODE_ENV = "production"
